#!/bin/bash 

#########################################################################
##  frankl (C) 2015              play_remote
##
##  See README or http://frank_l.bitbucket.org/stereoutils/player.html
##  for explanations.
#########################################################################

CARD="hw:0,0"
EXTRABYTESBUF=0
EXTRABYTESPLAY=0

#VERBOSE="--verbose --verbose"
AUDIOCOMPUTER=192.168.10.2
HOST=192.168.10.1
PORT=5570
SAMPLERATE=44100
BITLENGTH=32
SAMPLEFORMAT=S32_LE

trap "trap - SIGTERM && kill -- -$$ " SIGINT SIGTERM EXIT
# find input sample rate
SAMPLERATE=`sox --i "$1" | grep "Sample Rate" | cut -d: -f2 | sed -e "s/ //g"`

if [ "${SAMPLERATE}" = "96000" ]; then
  LOOPSPERSECOND=1500
  HW_BUFFER=4096
  EXTRABYTESPLAY=0
  BYTESPERSECOND=768000

elif [ "${SAMPLERATE}" = "48000" ]; then
  LOOPSPERSECOND=1500
  HW_BUFFER=2048
  EXTRABYTESPLAY=0
  BYTESPERSECOND=384000

elif [ "${SAMPLERATE}" = "88200" ]; then
  LOOPSPERSECOND=1050
  HW_BUFFER=4032
  EXTRABYTESPLAY=0
  BYTESPERSECOND=705600

elif [ "${SAMPLERATE}" = "44100" ]; then
  LOOPSPERSECOND=1050
  HW_BUFFER=7680
  EXTRABYTESPLAY=0
  BYTESPERSECOND=352800

elif [ "${SAMPLERATE}" = "192000" ]; then
  LOOPSPERSECOND=1500
  HW_BUFFER=8192
  EXTRABYTESPLAY=0
  BYTESPERSECOND=1536000
fi

cpupower frequency-set -u 3400MHz

#echo ${ORIGRATE}
#ENDING=${1##*.}

sox "$1" -t raw -e signed -b 32 /dev/shm/play.raw

cpupower frequency-set -u 800MHz -d 800MHz

# tell audio computer what to do, short sleep as startup time for sender
REMOTE="sleep 0.3;\
        taskset -c 3 chrt -f 90 playhrtmin --stripped ${VERBOSE} --host=${HOST} --port=${PORT} \
                     --sample-rate=${SAMPLERATE} \
                     --sample-format=${SAMPLEFORMAT} \
                     --loops-per-second=${LOOPSPERSECOND} --number-copies=2 --slow-copies \
                     --device=${CARD} --hw-buffer=${HW_BUFFER} \
                     --extra-bytes-per-second=${EXTRABYTESPLAY} \
                     --non-blocking-write --mmap" #--in-net-buffer-size=67200"

echo "${REMOTE}" |  nc -q 0 ${AUDIOCOMPUTER} 5501 

taskset -c 3 chrt -f 90 bufhrtmin --file=/dev/shm/play.raw --bytes-per-second=${BYTESPERSECOND} \
       --loops-per-second=${LOOPSPERSECOND} --port-to-write=${PORT} \
       --extra-bytes-per-second=${EXTRABYTESBUF} \
       ${VERBOSE} #--out-net-buffer-size=67200
